# Generated by Django 6.0.4 on 2026-06-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
