[project]
name = "art-backend"
version = "0.1.0"
description = "Art Backend Production Ready Structure"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.4",
    "django-cors-headers>=4.9.0",
    "django-ninja>=1.6.2",
    "djangorestframework>=3.17.1",
    "google-auth>=2.49.2",
    "mysqlclient>=2.2.8",
    "pyjwt>=2.12.1",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.46.0",
    "requests>=2.32.3",
    "Pillow>=10.3.0",
    "environs[django]>=14.1.0",
    "gunicorn>=26.0.0",
]
