# Generated by Django 6.0.5 on 2026-06-13 18:37

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_video_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, storage=apps.courses.models.VideoStorage(), upload_to='lessons/'),
        ),
    ]
